- src/Controller/LandingController.php
This will fix controller code formatting and therefore CI checks
> Fix controller code formatting

- package-lock.json
- package.json
- Adds expose-loader to webpack
> Add missing expose loader

- .docker/Dockerfile
- package.json
- build assets in intermediate image
- copy them to PHP and NGINX images
> Build assets in Dockerfile

- .github/workflows/docker.yml
- title
- built images are pushed to GitHub registry
> Add GitHub Actions Docker registry build

- .docker/Dockerfile
> Use .env in Docker container

- .github/workflows/docker.yml
- Auto redeployment of https://dev.armaforces.com
> Redeploy dev environment on pushes

- .docker/Dockerfile
- Adds translations to Dockerfile
> Add translations to Dockerfile

- .docker/Dockerfile
- .dockerignore
- nodejs and npm in dev image
- extended .dockerignore rules
> Add node to dev image

- templates/layout/_base.html.twig
- translations/messages.pl.yaml
> Add OpenGraph meta tags for nicer embeds

- .docker/php/docker-entrypoint.sh
> Auto run migrations when starting container

- assets/joinUs.scss
- assets/landing.scss
- templates/join_us.html.twig
- translations/messages.pl.yaml
> Add content to "join us" page

- .env
- title
- allows to start whole docker-compose stack without making any changes to default configuration
> Update default mysql dsn

- src/Controller/HomeController.php
- src/Controller/SecurityController.php
This will:
* fix some inconsistencies with controllers actions naming
> Fix controller actions names

- assets/app.scss
- templates/home/index/index.html.twig
> Fix logo text scaling on mobiles

- .github/workflows/docker.yml
> Add auto deployment of prod from master branch

- assets/app.scss
- assets/landing.scss
- templates/home/index/_partial/_missions.html.twig
- fix mission image scaling on index page
- fix blue navbar bg
- fix navbar not expanding (now navbar pushes content could be improved)
- fix navbar bg not transitioning smoothly 
Closes #40
> Fixes for mobile layouts

- docker-compose.override.yml
> Update imgproxy settings

- src/Service/Mission/Dto/MissionDto.php
- templates/home/index/_partial/_missions.html.twig
- templates/home/missions/missions.html.twig
- translations/messages.pl.yaml
> Center mission title, add number of enlisted players

- templates/home/missions/missions.html.twig
> Reverse display order of open missions

- docker-compose.override.yml
> Disable caching for dev docker mount

- src/Command/PermissionsMakeAdminCommand.php
> Make PermissionsMakeAdminCommand interactive

- .docker/php/docker-entrypoint.sh
> Ignore setfacl errors in container startup

- templates/_partial/_mission_widget.html.twig
- templates/home/missions/missions.html.twig
> Restore image lazy loading on missions page

- .docker/nginx/conf.d/default.conf
> Add static asset caching

- src/Enum/Mission/MissionStateEnum.php
- src/Service/Mission/Dto/MissionDto.php
- src/Service/Mission/MissionClient.php
- templates/_partial/_mission_widget.html.twig
- templates/home/index/_partial/_missions.html.twig
- templates/home/missions/missions.html.twig
- translations/messages.pl.yaml
Improved handling of nearest mission via mission state added to bot api
Fixes #50
> Handle mission state from bot api

- src/Twig/CalendarExtension.php
> Add [AF] tag to mission calendar events

- .docker/Dockerfile
- .github/workflows/docker.yml
- .gitignore
- config/packages/twig.yaml
- config/services.yaml
- src/Service/Version/VersionProvider.php
- src/Twig/VersionExtension.php
- templates/_partial/_footer.html.twig
- templates/_partial/_mission_widget.html.twig
- title
- VersionProvider
- VersionExtension
> Add version to footer

- .docker/php/docker-entrypoint.sh
- removed `composer install` on container start
- doctrine migrations will be ran only in prod
> Update PHP docker entrypoint

- src/Migrations/Version20200103010805.php
- src/Migrations/Version20200123221244.php
> Fix issue with old migrations and BC breaking changes to User entities

- .env
> Update default missions api url

- .docker/Dockerfile
> Update PHP to 7.4 and update XDebug to 2.9

- .env
- composer.json
- composer.lock
- config/api_platform/resources.yaml
- config/bundles.php
- config/doctrine/ModList/ModList.orm.xml
- config/packages/api_platform.yaml
- config/packages/framework.yaml
- config/packages/nelmio_cors.yaml
- config/routes/api_platform.yaml
- config/services.yaml
- phpstan.neon.dist
- src/Api/DataProvider/ModListByNameDataProvider.php
- src/Api/DataTransformer/ModListDetailsOutputDataTransformer.php
- src/Api/DataTransformer/ModListOutputDataTransformer.php
- src/Api/DataTransformer/ModOutputDataTransformer.php
- src/Api/Dto/ModListDetailsOutput.php
- src/Api/Dto/ModListOutput.php
- src/Api/Dto/ModOutput.php
- src/Entity/ModList/ModList.php
- src/Service/Serializer/CircularReferenceHandler.php
- symfony.lock
- add Api-Platform
- get ModList details by id
- get ModList details by name
- get ModLists list
> Add ModLists API

- config/packages/twig.yaml
- config/services.yaml
- templates/_partial/_footer.html.twig
- templates/_partial/_navbar.html.twig
- templates/base.html.twig
- templates/home/index/_partial/pl/_games.html.twig
- templates/home/index/index.html.twig
- templates/home/join_us/_partial/pl/join_steps.html.twig
- templates/home/join_us/join_us.html.twig
- templates/mod_list_public/launcher_preset_template.html.twig
This will:
* Add "global" namespace for all Twig variables that are global. This will prevent name conflicts between local variables returned by controller or declared directly inside templates especially "app" variable which is provided by default.
* Add some additional global variables
* Replace some hard-coded strings with these variables
> Twig globals improvements

- .github/workflows/security.yml
> Add Symfony security checker to CI

- templates/home/join_us/join_us.html.twig
> Fix Join Us page title concat

- composer.lock
This will:
* Update Symfony kernel package and fix CI
> Update Symfony kernel

- .docker/Dockerfile
This will:
* Include missing "migrations" directory in Docker image
> Include migrations directory

- config/doctrine/Mod/SteamWorkshopMod.orm.xml
- migrations/Version20201211150846.php
- src/Entity/Mod/SteamWorkshopMod.php
- src/Entity/Mod/SteamWorkshopModInterface.php
> Fix integer database column too short for ulong Steam Workshop IDs

- assets/modListPublic/modListCustomize.js
- templates/mod_list_public/customize.html.twig
> Fix parameter used for mod list download

- src/Twig/UserExtension.php
- templates/_partial/_navbar.html.twig
- Fix missing profile icon for users without avatar
- Fix missing profile icon if user changed avatar and has not re-loged
Closes #118
> Fix missing avatar/profile icon

- src/Api/DataTransformer/ModListOutputDataTransformer.php
- src/Service/Serializer/CircularReferenceHandler.php
- tests/unit/Service/Serializer/CircularReferenceHandlerTest.php
> Fix circular reference for UUiD

- assets/_bootstrap.scss
- assets/app.scss
- package-lock.json
- package.json
- templates/_partial/_navbar.html.twig
- templates/card.html.twig
- templates/home/index/_partial/pl/_gaming.html.twig
- templates/mod/form.html.twig
- templates/mod/list.html.twig
- templates/mod_group/form.html.twig
- templates/mod_group/list.html.twig
- templates/mod_list/form.html.twig
- templates/mod_list/list.html.twig
- templates/mod_list_public/customize.html.twig
- templates/mod_list_public/select.html.twig
- templates/user/list.html.twig
- Card layout for forms
- Card layout for tables/lists
- Badge with required mods amount on modlist download page
- Bigger navbar icons
> UX improvements

- assets/joinUs.scss
- assets/landing.scss
- Minor improvements for Join Us page on mobile devices
- Removal of navbar height animations on home page
> More UX improvements

- src/Form/ModGroup/DataTransformer/ModGroupFormDtoDataTransformer.php
- src/Validator/ModGroup/UniqueModGroupNameValidator.php
> Fix mod group validation

- src/Controller/ModListPublicController.php
> Remove customize route suffix

- src/Security/DiscordAuthenticator.php
> Update email on each login

- src/Form/Mod/ModFormType.php
- reorder based on frequency of used mod types
> Reorder mod types in mod creation form

- .github/workflows/docker.yml
- .github/workflows/tests.yml
- docker-compose.test.yml
Hopefully it will speed up container building in CI tests.
> CI assets caching

- .docker/Dockerfile
- .github/workflows/docker.yml
- .github/workflows/tests.yml
- Enable COMPOSE_DOCKER_CLI_BUILD
- Later copying of VERSION file to improve docker cache optimization
> CI build speed improvements

- src/Controller/ModListController.php
This will:
* title
Closes: #149
> Fix Mod List approved status on copy

- config/packages/framework.yaml
- title
- allows us to mount them to docker volume in our swarm environments and this will prevent user from being logged out on every deploy
> Sessions in app var

- composer.json
- composer.lock
- title
- in line with code quality tools
> Bump php version in composer.json

- src/Controller/ModListPublicController.php
> Add missing date and time to downloaded modlist filename

- Makefile
- phpstan.neon.dist
- src/Cache/CacheWarmer/BackgroundImageCacheWarmer.php
This will:
* Fix CI and code quality errors
> Fix code quality errors

- src/Controller/ModListPublicController.php
> Fix required mods download

- templates/_partial/navbar/_navbar_icons.html.twig
- templates/_partial/navbar/_navbar_links.html.twig
- templates/home/join_us/_partial/pl/join_steps.html.twig
- templates/home/missions/missions.html.twig
> Improve templates readability

- config/services.yaml
- src/Security/DiscordAuthenticator.php
This will:
* Improve Discord authenticator by reducing complexity 
* Remove calls to Discord API using user token
> Discord authenticator refactor

- config/packages/framework.yaml
> Add reverse proxy configuration for Symfony 5.2

- templates/_partial/_page_header.html.twig
- templates/mod_list_public/customize.html.twig
This will:
* title
Closes: #196
> Add mod list description on download page

- .docker/Dockerfile
- .docker/php/conf.d/docker-php-ext-xdebug.ini
- .docker/php/docker-entrypoint.sh
- .docker/php/scripts/xoff.sh
- .docker/php/scripts/xon.sh
This will:
* Improve how xdebug can be switched on and off.
Now `xoff` will unload xdebug entirely instead of disabling remote debugging. This will improve performance.
> Improve xdebug configuration

- src/Controller/ModListPublicController.php
- src/Test/Traits/AssertsTrait.php
> Restore old filename of downloaded modlist

- config/packages/framework.yaml
> Increase session duration to 180 days

- composer.lock
> Update packages with known vulnerabilities to latest versions

- templates/mod_list_public/launcher_preset_template.html.twig
> Remove invalid meta tag

- templates/mod_list/list.html.twig
- templates/mod_list_public/select.html.twig
Thjs will:
* title
Closes: #211
> Add missing DLC icons on Mod List download page

- config/doctrine/Dlc/Dlc.orm.xml
- migrations/Version20210625211018.php
- src/Api/DataTransformer/DlcOutputDataTransformer.php
- src/Api/Dto/DlcOutput.php
- src/Entity/Dlc/Dlc.php
- src/Entity/Dlc/DlcInterface.php
- src/Form/Dlc/DataTransformer/DlcFormDtoDataTransformer.php
- src/Form/Dlc/DlcFormType.php
- src/Form/Dlc/Dto/DlcFormDto.php
- src/Form/Mod/Dto/ModFormDto.php
- src/Validator/Dlc/UniqueDirectoryDlc.php
- src/Validator/Dlc/UniqueDirectoryDlcValidator.php
- src/Validator/WindowsDirectoryName.php
- src/Validator/WindowsDirectoryNameValidator.php
- translations/messages.pl.yaml
- translations/validators.pl.yaml
This will:
* Add support for DLC directories
* Update existing DLCs with default directory names
> Add support for DLC directory

- Makefile
- src/Command/PermissionsMakeAdminCommand.php
This will:
* Add option to create first admin user with full permissions instead of only basic user permissions.
> Add option to create admin with full permissions

- translations/messages.pl.yaml
This will:
* title
Closes #220
> Fix typo on join us page

- config/packages/framework.yaml
Hopefully, this will fix sessions expiring too soon.
> Increase GC time for sessions

- src/Api/Controller/GetModListByNameAction.php
- tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
- tests/functional/Api/Controller/ModList/GetModListsActionTest.php
This will:
* Return a 404 not found response when no mod list by name found
Closes: #222
> Fix error response when no mod list found

- config/packages/api_platform.yaml
> Add authentication to api docs page

- assets/app.js
- assets/app.scss
- templates/_partial/dlc_tabs/_dlc_tabs_table.html.twig
- templates/_partial/mod_group_tabs/_mod_group_tabs_table.html.twig
- templates/_partial/mod_tabs/_mod_tabs_table.html.twig
- templates/mod_list_public/_partial/_optional_mods_tab.html.twig
- templates/mod_list_public/select.html.twig
- templates/user_group/_partial/_users_table.html.twig
This will:
* Add default row action for some of the tables
* Clicking on row that has checkbox (switch) in it will toggle that checkbox
* Clicking row on modlist select page will now open modlist customization page
Closes: #233
> Add default row actions

- src/Api/DataTransformer/ModList/ModListDetailsOutputDataTransformer.php
- src/Api/DataTransformer/ModList/ModListOutputDataTransformer.php
- src/Api/Output/ModList/ModListOutput.php
- tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
- tests/functional/Api/Controller/ModList/GetModListsActionTest.php
- tests/functional/Api/Controller/ModList/GetModListsByIdActionTest.php
This will:
* Add `active` and `approved` properties to the Mod List API object
> Add additional data to Mod List API object

- config/packages/framework.yaml
- config/services.yaml
- migrations/Version20220117223431.php
This will:
Change DB session handler to PDO because we can't afford a proper storage infrastructure
> Change session handler to PDO

- config/packages/prod/deprecations.yaml
> Revert changes to deprecation log config

- src/Service/LegacyModListImport/ModListImport.php
> Fix flush in mod list import command

- Makefile
- docker-compose.test.yml
- phpstan.neon.dist
- tests/unit/EventSubscriber/Doctrine/EntityBlamableSubscriberTest.php
> Enable PHPStan in tests

- .github/workflows/security.yml
- composer.lock
> Use master for symfony security checker

- composer.lock
- src/Service/Mission/Dto/MissionDto.php
- tests/unit/Service/MissionClientTest.php
- title
- The bot is retarded and sometimes "drops" the needed field temporarily xD
> Handle empty "modlistName" in MissionDto

- .docker/Dockerfile
- title
- also use static version instead of `latest`
> Use smaller docker image for composer binary

- src/Command/ImportModListsCommand.php
- src/Controller/HomeController.php
- src/Controller/ModListPublicController.php
- src/Form/Dlc/DataTransformer/DlcFormDtoDataTransformer.php
- src/Form/Mod/DataTransformer/ModFormDtoDataTransformer.php
- src/Service/LegacyModListImport/DtoToEntityConverter.php
- src/Service/LegacyModListImport/DtoToEntityConverterInterface.php
- src/Service/LegacyModListImport/ModListCsvReader.php
- src/Service/LegacyModListImport/ModListCsvReaderInterface.php
- src/Service/LegacyModListImport/ModListImport.php
- src/Service/LegacyModListImport/ModListImportInterface.php
- src/Service/Mission/MissionClient.php
- src/Service/Mission/MissionClientInterface.php
- src/Service/Steam/SteamApiClient.php
- src/Service/Steam/SteamApiClientInterface.php
- src/Service/Version/VersionProvider.php
- src/Service/Version/VersionProviderInterface.php
- src/Twig/VersionExtension.php
- src/Validator/Dlc/SteamStoreArma3DlcUrlValidator.php
- src/Validator/Mod/SteamWorkshopArma3ModUrlValidator.php
> Add interfaces to services

- src/Api/DataTransformer/Attendance/AttendanceInputDataTransformer.php
- src/Api/Input/Attendance/AttendanceInput.php
- src/Form/Dlc/Dto/DlcFormDto.php
- src/Form/Mod/Dto/ModFormDto.php
- src/Form/ModGroup/Dto/ModGroupFormDto.php
- src/Form/ModList/Dto/ModListFormDto.php
- src/Form/User/Dto/UserFormDto.php
- src/Form/UserGroup/Dto/UserGroupFormDto.php
- src/Validator/Attendance/UniqueAttendance.php
- src/Validator/Dlc/SteamStoreArma3DlcUrl.php
- src/Validator/Dlc/UniqueDirectoryDlc.php
- src/Validator/Dlc/UniqueSteamStoreDlc.php
- src/Validator/Mod/SteamWorkshopArma3ModUrl.php
- src/Validator/Mod/UniqueDirectoryMod.php
- src/Validator/Mod/UniqueSteamWorkshopMod.php
- src/Validator/ModGroup/UniqueModGroupName.php
- src/Validator/ModList/UniqueModListName.php
- src/Validator/SteamProfileId.php
- src/Validator/User/UniqueUserSteamId.php
- src/Validator/UserGroup/UniqueUserGroupName.php
- src/Validator/WindowsDirectoryName.php
> Refactor validators; replace annotations with attributes

- src/Service/Mission/MissionStore.php
> Fix missing union return type

- src/Entity/User/User.php
- src/Security/Authenticator/DiscordAuthenticator.php
- src/Security/Model/ApiTokenUser.php
- src/Security/Traits/UserInterfaceTrait.php
> Fix use externalId as Passport user identifier

- src/Controller/Mod/UpdateAction.php
- src/Controller/ModGroup/UpdateAction.php
- src/Controller/ModList/CopyAction.php
- src/Controller/ModList/UpdateAction.php
> Fix missing voter subject

- templates/mod_list_public/_partial/_optional_mods_tab.html.twig
- templates/mod_list_public/_partial/_required_mods_tab.html.twig
> Fix mods display condition

- src/Validator/Dlc/SteamStoreArma3DlcUrl.php
> Fix DLC validator

- src/Form/Mod/Dto/ModFormDto.php
- src/Validator/Mod/ModSourceAndType.php
- src/Validator/Mod/ModSourceAndTypeValidator.php
- translations/validators.pl.yaml
> Replace expression assert with custom validator

- .docker/Dockerfile
- package-lock.json
- package.json
- webpack.config.js
> Update frontend dependencies

- src/Repository/UserGroup/UserGroupRepository.php
> Remove invalid typehint

- src/EventSubscriber/Doctrine/ModGroupUpdatedSubscriber.php
- src/Repository/ModList/ModListRepository.php
- src/Service/ModListUpdateService/ModListUpdateService.php
- src/Service/ModListUpdateService/ModListUpdateServiceInterface.php
This will:
- fix case in which Mods were unassigned from Mod Group on update
This version is for master branch
> Fix issue with mods lost on update - master

- src/EventSubscriber/Doctrine/ModGroupUpdatedSubscriber.php
- src/Service/ModListUpdateService/ModListUpdateService.php
- src/Service/ModListUpdateService/ModListUpdateServiceInterface.php
This will:
- fix case in which Mods were unassigned from Mod Group on update
This version is for dev branch
> Fix issue with mods lost on update - dev

- phpstan.neon.dist
- src/Service/ModListUpdateService/ModListUpdateService.php
> Remove call to deprecated service

- src/Repository/ModList/ModListRepository.php
> Remove unused repository method

- README.md
> Fix readme workflows badge

- Makefile
- tests/integration/Service/Version/VersionProviderTest.php
- tests/tests_namespace_checker.php
- tests/unit/Service/Mission/MissionClientTest.php
> Add tests namespace checker function; fix namespaces

- .docker/php/docker-entrypoint.sh
- .github/workflows/application.yml
- docker-compose.override.yml
- docker-compose.test.yml
> Improve mysql container healthcheck

- assets/mod/modForm.js
> Use mod source list to determine available fields and options

- composer.json
- composer.lock
- src/DataFixtures/Mod/Optional/AceInteractionMenuExpansionModFixture.php
- src/DataFixtures/Mod/Required/ArmaForcesModsModFixture.php
- src/DataFixtures/Mod/Required/Broken/ArmaForcesAceMedicalModFixture.php
- src/DataFixtures/Mod/Required/Deprecated/LegacyArmaForcesModsModFixture.php
- src/DataFixtures/Mod/Required/Disabled/ArmaForcesJbadBuildingFixModFixture.php
- src/DataFixtures/ModGroup/RhsModGroupFixture.php
- src/DataFixtures/ModList/DefaultModListFixture.php
- src/Entity/AbstractBlamableEntity.php
- src/Entity/AbstractEntity.php
- src/Test/Traits/TimeTrait.php
- tests/functional/Api/Controller/ModList/GetModListByNameActionTest.php
- tests/functional/Api/Controller/ModList/GetModListsActionTest.php
- tests/functional/Api/Controller/ModList/GetModListsByIdActionTest.php
This will:
- use symfony/clock component to freeze time when creating fixtures
- restore previously removed tests
> Use clock component

- migrations/Version20231021222125.php
- migrations/Version20231022205021.php
This will:
- sync changes between master and dev
> Sync dev master

- src/Security/Authenticator/DiscordAuthenticator.php
> Fix store SteamId on user login

- templates/_partial/permissions/form.html.twig
- templates/user/form.html.twig
- templates/user_group/_partial/combo_tabs/_combo_tabs_content.html.twig
> Fix use common template for both user and user group permissions

- src/Api/Controller/GetModListByNameAction.php
- src/Controller/ModListPublic/SelectAction.php
- src/Repository/ModList/ModListRepository.php
> Use dedicated repository method to fetch single mod list

- src/Controller/Security/ConnectCheckAction.php
- src/Controller/Security/LogoutAction.php
> Remove unused dependency

- src/Form/ModList/Dto/ModListFormDto.php
- src/Form/User/Dto/UserFormDto.php
> Use attributes instead of annotations

- src/Controller/UserGroup/DeleteAction.php
- src/Controller/UserGroup/UpdateAction.php
> Fix route argument name

- src/Form/Dlc/Dto/DlcFormDto.php
- src/Validator/Dlc/SteamStoreArma3DlcUrlValidator.php
- src/Validator/Dlc/UniqueDirectoryDlcValidator.php
- src/Validator/Mod/UniqueDirectoryModValidator.php
- src/Validator/ModGroup/UniqueModGroupNameValidator.php
- src/Validator/ModList/UniqueModListNameValidator.php
- src/Validator/User/UniqueUserSteamIdValidator.php
- src/Validator/UserGroup/UniqueUserGroupNameValidator.php
> Improve handling of empty values in validators

- src/Form/Dlc/Dto/DlcFormDto.php
- src/Form/Mod/Dto/ModFormDto.php
> Change validation message target to specific field instead of form

- src/Validator/WindowsDirectoryName.php
> Fix directory validator regex

- src/Validator/Attendance/UniqueAttendance.php
- src/Validator/Dlc/SteamStoreArma3DlcUrl.php
- src/Validator/Dlc/UniqueDirectoryDlc.php
- src/Validator/Dlc/UniqueSteamStoreDlc.php
- src/Validator/Mod/SteamWorkshopArma3ModUrl.php
- src/Validator/Mod/UniqueDirectoryMod.php
- src/Validator/Mod/UniqueSteamWorkshopMod.php
- src/Validator/ModGroup/UniqueModGroupName.php
- src/Validator/ModList/UniqueModListName.php
- src/Validator/SteamProfileId.php
- src/Validator/User/UniqueUserSteamId.php
- src/Validator/UserGroup/UniqueUserGroupName.php
- src/Validator/WindowsDirectoryName.php
- tests/functional/Api/Controller/Attendance/CreateAttendanceActionTest.php
- translations/validators.pl.yaml
> Make translation messages consistent with Symfony validators

- README.md
> Update readme oauth integration description
